---
title: R 글꼴 변경
author: 이청파
date: '2020-06-05'
slug: 'r/3'
categories:
  - R
tags:
  - R
  - R studio
  - 글꼴
editor_options: 
  chunk_output_type: inline
output: 
  blogdown::html_page:
    toc: true
    highlight: tango
    number_section: true
    self_contained: true
---


 
# 글꼴 설치


코딩시 주로 사용하는 한글 글꼴


- [D2 Coding 글꼴](https://github.com/naver/d2codingfont)

- [네이버 나눔코딩 글꼴](https://github.com/naver/nanumfont/blob/master/README.md)

트루타입 글꼴 설치 가능

D2Coding 선호 : D2CodingLigature는 축약으로 직관적이나, 명확한 코드를 선호하기에 D2Coding를 추천한다.

# R에 적용

```{r,eval=F}
install.packages(extrafont)
library(extrafont)
font_import(pattern = "D2")
```

글꼴 적용 후 Tools-global options-Appearence에서 설정 가능

# Rmd body

```{r eval=FALSE}

<style>
body{
     font-family: 나눔바른고딕;
}
</style>
```

다음과 형태로 body 변환 가능



# 알아볼 패키지

showtext 예시

(CRAN에 패키지 미설치로 인해 추후 보완 예정)

```{r,eval=F}
install.packages("KoNLP") # CRAN에 없으므로 다른 방벙 알아서
install.packages("devtools")
devtools::install_github("lchiffon/wordcloud2")
```


```{r, eval =F}
library(KoNLP)
library(wordcloud2)


dt <- readLines('./data/blog_text.txt', encoding = 'UTF-8')

# 하다가 포기
wordcloud2(data=dt,fontFamily = '나눔바른고딕')
```

